from __future__ import annotations


TABLE_LABELS = {
    "organizations": "主体库",
    "experts": "专家库",
    "interviews": "访谈纪要库",
    "industry_relationships": "产业链关系",
    "papers": "论文",
    "patents": "专利",
    "financing_events": "融资事件",
    "policies": "产业政策",
    "products": "产品商业化",
    "research_tasks": "调研任务",
}

CRUD_FIELDS = {
    "organizations": [
        "name",
        "short_name",
        "organization_type",
        "industry_chain_role",
        "country",
        "city",
        "founded_year",
        "website",
        "market_segment",
        "tech_routes",
        "products_services",
        "commercialization_stage",
        "financing_stage",
        "total_financing",
        "latest_financing_date",
        "investors",
        "valuation_range",
        "revenue_status",
        "key_team",
        "customers",
        "suppliers",
        "competitors",
        "advantages",
        "risks",
        "tracking_status",
        "investment_priority",
        "cooperation_priority",
        "relevance_to_our_team",
        "credibility",
        "verification_status",
        "notes",
    ],
    "experts": [
        "name",
        "institution",
        "title",
        "country",
        "market_segment",
        "tech_routes",
        "expertise",
        "representative_achievements",
        "representative_papers",
        "representative_patents",
        "related_organizations",
        "industrialization_experience",
        "interview_value",
        "credibility",
        "relevance_to_our_team",
        "contact",
        "key_views",
        "risk_notes",
        "notes",
    ],
    "interviews": [
        "title",
        "interviewee",
        "interviewee_type",
        "interview_date",
        "interviewer",
        "market_segment",
        "tech_routes",
        "related_organizations",
        "related_experts",
        "topic",
        "raw_notes",
        "key_points",
        "verifiable_facts",
        "subjective_judgments",
        "important_conclusions",
        "risks",
        "follow_up_actions",
        "credibility",
        "sensitivity",
        "information_type",
        "verification_status",
    ],
    "industry_relationships": [
        "source_organization_id",
        "target_organization_id",
        "relationship_type",
        "market_segment",
        "tech_routes",
        "description",
        "event_date",
        "source",
        "credibility",
        "verification_status",
        "notes",
    ],
    "research_tasks": [
        "task_title",
        "task_type",
        "related_market_segment",
        "related_tech_route",
        "related_organization",
        "related_expert",
        "question_to_verify",
        "owner",
        "status",
        "due_date",
        "notes",
    ],
}

