from __future__ import annotations

import sqlite3
from datetime import datetime


NOW = datetime.now().isoformat(timespec="seconds")


def insert_many(conn: sqlite3.Connection, table: str, rows: list[dict]) -> None:
    if not rows:
        return
    columns = list(rows[0].keys())
    placeholders = ", ".join(["?"] * len(columns))
    conn.executemany(
        f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})",
        [[row.get(col) for col in columns] for row in rows],
    )


def seed_database(conn: sqlite3.Connection) -> None:
    market_segments = [
        {"name": "量子市场总体", "parent_id": None, "description": "覆盖量子计算、量子通信、量子精密测量的产业总览。"},
        {"name": "量子计算", "parent_id": 1, "description": "面向通用计算、专用模拟、量子云平台和科研仪器的市场方向。"},
        {"name": "量子通信", "parent_id": 1, "description": "面向 QKD、量子网络、量子安全通信和随机数的市场方向。"},
        {"name": "量子精密测量", "parent_id": 1, "description": "面向时间频率、磁场、重力、惯性和工业检测的市场方向。"},
    ]
    tech_routes = [
        {
            "name": "离子阱",
            "market_segment": "量子计算",
            "principle": "利用电磁场囚禁离子，以激光或微波操控量子态并实现高保真门操作。",
            "core_components": "真空系统、离子阱芯片、窄线宽激光器、AOM/EOM、成像系统、测控电子学。",
            "key_metrics": "单/双比特门保真度、相干时间、串扰、离子装载率、系统稳定运行时间。",
            "maturity": "工程样机到小规模云端开放阶段",
            "engineering_challenges": "系统复杂度高、光路和真空长期稳定性、扩展互连和自动化运维。",
            "commercialization_path": "科研仪器、云平台、专用量子模拟、教育培训。",
            "notes": "适合重点跟踪供应链国产替代与整机交付案例。",
        },
        {
            "name": "超导量子",
            "market_segment": "量子计算",
            "principle": "基于超导约瑟夫森结构造人工原子，通过微波脉冲实现量子门。",
            "core_components": "稀释制冷机、超导芯片、微波链路、低温放大器、AWG/ADC、控制软件。",
            "key_metrics": "比特数量、门保真度、退相干时间、芯片良率、低温系统可用性。",
            "maturity": "云平台和中等规模系统迭代阶段",
            "engineering_challenges": "低温工程、芯片一致性、连线规模化、纠错开销。",
            "commercialization_path": "云平台、算法验证、科研服务、专用模拟。",
            "notes": "资本关注度高，但商业化确定性仍依赖有效应用场景。",
        },
        {
            "name": "中性原子",
            "market_segment": "量子计算",
            "principle": "用光镊阵列捕获中性原子，以里德堡相互作用实现可编程量子模拟与门操作。",
            "core_components": "激光器、光镊阵列、真空腔、成像系统、控制电子学。",
            "key_metrics": "原子装载率、阵列规模、门保真度、重排速度、相干时间。",
            "maturity": "快速扩展的工程样机阶段",
            "engineering_challenges": "高保真门、系统自动化、激光稳定性和应用验证。",
            "commercialization_path": "量子模拟、云服务、科研仪器。",
            "notes": "近年来论文活跃，适合跟踪产业化节奏。",
        },
        {
            "name": "QKD",
            "market_segment": "量子通信",
            "principle": "利用量子态不可克隆和测量扰动特性实现密钥分发。",
            "core_components": "单光子源/弱相干光源、调制器、单光子探测器、同步与密钥管理系统。",
            "key_metrics": "成码率、传输距离、误码率、系统稳定性、安全认证。",
            "maturity": "示范项目到行业客户验证阶段",
            "engineering_challenges": "成本、网络规模化、标准化、与现有安全系统融合。",
            "commercialization_path": "政务、金融、电力、运营商安全网络。",
            "notes": "商业化更接近项目制和安全基础设施路径。",
        },
        {
            "name": "NV色心",
            "market_segment": "量子精密测量",
            "principle": "利用金刚石 NV 色心自旋态对磁场、温度、应力等物理量的响应实现高灵敏传感。",
            "core_components": "金刚石材料、微波控制、光学激发与读出、磁屏蔽、算法软件。",
            "key_metrics": "灵敏度、空间分辨率、工作温区、稳定性、样品兼容性。",
            "maturity": "科研仪器和部分应用验证阶段",
            "engineering_challenges": "材料一致性、系统标定、场景适配和成本控制。",
            "commercialization_path": "半导体检测、生命科学成像、材料表征、工业无损检测。",
            "notes": "下游需求真实性是判断重点。",
        },
        {
            "name": "冷原子传感",
            "market_segment": "量子精密测量",
            "principle": "利用冷原子干涉对重力、加速度、旋转和时间频率进行高精度测量。",
            "core_components": "激光系统、真空系统、磁屏蔽、原子源、光机结构、控制软件。",
            "key_metrics": "灵敏度、漂移、体积功耗、环境适应性、外场运行稳定性。",
            "maturity": "工程样机到示范应用阶段",
            "engineering_challenges": "小型化、鲁棒性、现场部署和长期免维护。",
            "commercialization_path": "导航定位、资源勘探、国防航天、地球物理测量。",
            "notes": "与系统工程和核心部件能力强相关。",
        },
    ]
    insert_many(conn, "market_segments", market_segments)
    insert_many(conn, "tech_routes", tech_routes)

    organizations = [
        {
            "name": "华光窄线宽激光技术有限公司",
            "short_name": "华光激光",
            "organization_type": "上游核心零部件企业",
            "industry_chain_role": "上游",
            "country": "中国",
            "city": "武汉",
            "founded_year": "2017",
            "website": "https://example.com/laser",
            "market_segment": "综合",
            "tech_routes": "离子阱;冷原子传感;NV色心",
            "products_services": "窄线宽激光器、稳频模块、光学频率锁定系统",
            "commercialization_stage": "小批量交付",
            "financing_stage": "A轮",
            "total_financing": "数千万元",
            "latest_financing_date": "2025-04-12",
            "investors": "启明量子基金",
            "valuation_range": "未披露",
            "revenue_status": "科研客户收入增长",
            "key_team": "激光稳频和光机系统团队",
            "customers": "离子阱整机企业;冷原子传感团队",
            "suppliers": "光学元件厂商",
            "competitors": "进口窄线宽激光供应商",
            "advantages": "交付响应快，具备定制波长能力",
            "risks": "高端器件仍依赖进口",
            "tracking_status": "持续跟踪",
            "investment_priority": "A",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "高",
            "verification_status": "已验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "上游卡点属性较强，适合访谈。",
        },
        {
            "name": "北辰真空系统有限公司",
            "short_name": "北辰真空",
            "organization_type": "上游核心零部件企业",
            "industry_chain_role": "上游",
            "country": "中国",
            "city": "北京",
            "founded_year": "2015",
            "website": "https://example.com/vacuum",
            "market_segment": "综合",
            "tech_routes": "离子阱;中性原子;冷原子传感",
            "products_services": "UHV 真空腔、离子泵、烘烤系统、真空集成服务",
            "commercialization_stage": "规模销售",
            "financing_stage": "未融资",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "稳定收入",
            "key_team": "真空工程团队",
            "customers": "高校科研院所;量子整机公司",
            "suppliers": "真空泵和阀门厂商",
            "competitors": "海外 UHV 厂商",
            "advantages": "工程交付经验丰富",
            "risks": "极限真空指标需持续验证",
            "tracking_status": "已访谈",
            "investment_priority": "B",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "高",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "判断",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "适合作为供应链访谈对象。",
        },
        {
            "name": "极低温科学仪器股份有限公司",
            "short_name": "极低温",
            "organization_type": "上游核心零部件企业",
            "industry_chain_role": "上游",
            "country": "中国",
            "city": "合肥",
            "founded_year": "2019",
            "website": "https://example.com/cryogenic",
            "market_segment": "量子计算",
            "tech_routes": "超导量子",
            "products_services": "稀释制冷机、低温测量链路、低温工程服务",
            "commercialization_stage": "工程样机",
            "financing_stage": "Pre-A轮",
            "total_financing": "数千万元",
            "latest_financing_date": "2025-08-20",
            "investors": "科创产业基金",
            "valuation_range": "未披露",
            "revenue_status": "示范交付",
            "key_team": "低温物理与制冷工程团队",
            "customers": "超导量子计算实验室",
            "suppliers": "低温阀门;压缩机",
            "competitors": "海外稀释制冷机厂商",
            "advantages": "国产替代价值高",
            "risks": "可靠性和批量交付仍需验证",
            "tracking_status": "已接触",
            "investment_priority": "A",
            "cooperation_priority": "B",
            "relevance_to_our_team": "中",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "判断",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "超导路线关键上游。",
        },
        {
            "name": "星衡测控电子有限公司",
            "short_name": "星衡测控",
            "organization_type": "上游核心零部件企业",
            "industry_chain_role": "上游",
            "country": "中国",
            "city": "上海",
            "founded_year": "2020",
            "website": "https://example.com/control",
            "market_segment": "综合",
            "tech_routes": "超导量子;离子阱;NV色心",
            "products_services": "AWG、FPGA 控制器、DAC/ADC、同步时钟模块",
            "commercialization_stage": "小批量交付",
            "financing_stage": "天使轮",
            "total_financing": "千万元级",
            "latest_financing_date": "2024-12-05",
            "investors": "硬科技天使基金",
            "valuation_range": "未披露",
            "revenue_status": "早期收入",
            "key_team": "高速电子学与量子控制软件团队",
            "customers": "高校;量子计算整机企业",
            "suppliers": "高速芯片供应商",
            "competitors": "通用仪器厂商",
            "advantages": "软硬件一体化",
            "risks": "高端芯片供应风险",
            "tracking_status": "持续跟踪",
            "investment_priority": "A",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "推测",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "多路线共用上游，有平台化价值。",
        },
        {
            "name": "棱镜光学元件有限公司",
            "short_name": "棱镜光学",
            "organization_type": "上游核心零部件企业",
            "industry_chain_role": "上游",
            "country": "中国",
            "city": "长春",
            "founded_year": "2012",
            "website": "https://example.com/optics",
            "market_segment": "综合",
            "tech_routes": "离子阱;中性原子;QKD;冷原子传感",
            "products_services": "高反镜、偏振器、光学镀膜、精密光机组件",
            "commercialization_stage": "规模销售",
            "financing_stage": "未融资",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "稳定收入",
            "key_team": "光学加工与镀膜团队",
            "customers": "科研仪器厂商;QKD设备商",
            "suppliers": "光学玻璃供应商",
            "competitors": "进口光学元件厂商",
            "advantages": "成本和交期优势",
            "risks": "极限损耗和一致性指标需验证",
            "tracking_status": "未接触",
            "investment_priority": "B",
            "cooperation_priority": "B",
            "relevance_to_our_team": "中",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "通用上游供应商。",
        },
        {
            "name": "云阱量子计算有限公司",
            "short_name": "云阱量子",
            "organization_type": "整机或整体解决方案提供商",
            "industry_chain_role": "中游",
            "country": "中国",
            "city": "深圳",
            "founded_year": "2021",
            "website": "https://example.com/ionq",
            "market_segment": "量子计算",
            "tech_routes": "离子阱",
            "products_services": "离子阱量子计算整机、量子云访问、控制软件",
            "commercialization_stage": "工程样机",
            "financing_stage": "A轮",
            "total_financing": "1.2亿元",
            "latest_financing_date": "2025-06-18",
            "investors": "湾区科创基金;高校成果转化基金",
            "valuation_range": "10-20亿元",
            "revenue_status": "科研客户试用",
            "key_team": "离子阱实验和系统工程团队",
            "customers": "高校;科研院所;云平台客户",
            "suppliers": "华光激光;北辰真空;星衡测控",
            "competitors": "其他离子阱整机公司",
            "advantages": "系统集成和软件控制能力",
            "risks": "规模化和真实应用场景仍待验证",
            "tracking_status": "已尽调",
            "investment_priority": "A",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "高",
            "verification_status": "已验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "整机标的，适合持续访谈。",
        },
        {
            "name": "安密量子通信系统有限公司",
            "short_name": "安密量通",
            "organization_type": "整机或整体解决方案提供商",
            "industry_chain_role": "中游",
            "country": "中国",
            "city": "济南",
            "founded_year": "2016",
            "website": "https://example.com/qkd",
            "market_segment": "量子通信",
            "tech_routes": "QKD;量子安全通信",
            "products_services": "QKD设备、密钥管理平台、量子安全网络方案",
            "commercialization_stage": "示范项目",
            "financing_stage": "B轮",
            "total_financing": "3亿元",
            "latest_financing_date": "2024-11-10",
            "investors": "国资平台;通信产业基金",
            "valuation_range": "20-30亿元",
            "revenue_status": "项目制收入",
            "key_team": "通信系统和密码安全团队",
            "customers": "通信运营商;政务云;金融客户",
            "suppliers": "单光子探测器厂商;光学元件厂商",
            "competitors": "传统密码安全厂商;量子通信设备商",
            "advantages": "行业项目经验",
            "risks": "标准化和规模复制难度",
            "tracking_status": "已接触",
            "investment_priority": "B",
            "cooperation_priority": "B",
            "relevance_to_our_team": "中",
            "credibility": "高",
            "verification_status": "已验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "通信方向商业化较早。",
        },
        {
            "name": "星图量子测量科技有限公司",
            "short_name": "星图测量",
            "organization_type": "整机或整体解决方案提供商",
            "industry_chain_role": "中游",
            "country": "中国",
            "city": "杭州",
            "founded_year": "2022",
            "website": "https://example.com/sensing",
            "market_segment": "量子精密测量",
            "tech_routes": "NV色心;冷原子传感",
            "products_services": "量子磁力仪、冷原子重力仪、工业检测设备",
            "commercialization_stage": "小批量交付",
            "financing_stage": "Pre-A轮",
            "total_financing": "5000万元",
            "latest_financing_date": "2025-03-30",
            "investors": "先进制造基金",
            "valuation_range": "5-10亿元",
            "revenue_status": "示范项目和科研仪器收入",
            "key_team": "传感器系统和场景应用团队",
            "customers": "电网公司;工业检测客户;高校",
            "suppliers": "华光激光;棱镜光学;北辰真空",
            "competitors": "传统高端传感器厂商",
            "advantages": "场景适配能力强",
            "risks": "量子优势需在现场验证",
            "tracking_status": "已访谈",
            "investment_priority": "A",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "判断",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "精密测量方向值得优先看真实客户反馈。",
        },
        {
            "name": "东湖量子信息研究院",
            "short_name": "东湖量研院",
            "organization_type": "高校科研院所",
            "industry_chain_role": "支撑机构",
            "country": "中国",
            "city": "武汉",
            "founded_year": "2018",
            "website": "https://example.com/institute",
            "market_segment": "综合",
            "tech_routes": "离子阱;超导量子;QKD",
            "products_services": "基础研究、公共平台、成果转化",
            "commercialization_stage": "科研平台",
            "financing_stage": "",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "",
            "key_team": "量子信息科研团队",
            "customers": "政府平台;企业联合实验室",
            "suppliers": "",
            "competitors": "",
            "advantages": "专家资源密集",
            "risks": "产业化机制待观察",
            "tracking_status": "持续跟踪",
            "investment_priority": "B",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "高",
            "verification_status": "已验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "专家和成果转化来源。",
        },
        {
            "name": "华东通信运营商集团",
            "short_name": "华东运营商",
            "organization_type": "下游客户或应用方",
            "industry_chain_role": "下游",
            "country": "中国",
            "city": "南京",
            "founded_year": "1998",
            "website": "https://example.com/operator",
            "market_segment": "量子通信",
            "tech_routes": "QKD;量子安全通信",
            "products_services": "通信网络、政企专线、安全通信服务",
            "commercialization_stage": "采购验证",
            "financing_stage": "",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "",
            "key_team": "政企网络和安全业务团队",
            "customers": "政企客户",
            "suppliers": "安密量通",
            "competitors": "",
            "advantages": "客户网络和示范项目资源",
            "risks": "采购周期长",
            "tracking_status": "已接触",
            "investment_priority": "C",
            "cooperation_priority": "A",
            "relevance_to_our_team": "中",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "判断",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "QKD 下游典型客户。",
        },
        {
            "name": "国网量测技术中心",
            "short_name": "国网量测",
            "organization_type": "下游客户或应用方",
            "industry_chain_role": "下游",
            "country": "中国",
            "city": "北京",
            "founded_year": "2009",
            "website": "https://example.com/grid",
            "market_segment": "量子精密测量",
            "tech_routes": "NV色心;冷原子传感",
            "products_services": "电网设备检测、地下设施探测、时频同步",
            "commercialization_stage": "示范项目",
            "financing_stage": "",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "",
            "key_team": "电力设备检测团队",
            "customers": "",
            "suppliers": "星图测量",
            "competitors": "传统检测仪器供应商",
            "advantages": "应用场景明确",
            "risks": "对可靠性和标准化要求高",
            "tracking_status": "已访谈",
            "investment_priority": "C",
            "cooperation_priority": "A",
            "relevance_to_our_team": "高",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "观点",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "验证真实需求的重要下游。",
        },
        {
            "name": "启明量子基金",
            "short_name": "启明量子",
            "organization_type": "投资机构",
            "industry_chain_role": "支撑机构",
            "country": "中国",
            "city": "上海",
            "founded_year": "2020",
            "website": "https://example.com/fund",
            "market_segment": "综合",
            "tech_routes": "离子阱;超导量子;冷原子传感",
            "products_services": "硬科技股权投资",
            "commercialization_stage": "",
            "financing_stage": "",
            "total_financing": "",
            "latest_financing_date": "",
            "investors": "",
            "valuation_range": "",
            "revenue_status": "",
            "key_team": "硬科技投资团队",
            "customers": "",
            "suppliers": "",
            "competitors": "",
            "advantages": "产业资源和资金",
            "risks": "估值周期波动",
            "tracking_status": "已接触",
            "investment_priority": "B",
            "cooperation_priority": "B",
            "relevance_to_our_team": "中",
            "credibility": "中",
            "verification_status": "待验证",
            "source": "示例数据",
            "source_link": "",
            "entered_by": "系统",
            "information_type": "事实",
            "created_at": NOW,
            "updated_at": NOW,
            "notes": "可用于交叉验证融资信息。",
        },
    ]
    insert_many(conn, "organizations", organizations)

    org_id = {row["name"]: row["id"] for row in conn.execute("SELECT id, name FROM organizations").fetchall()}
    insert_many(
        conn,
        "upstream_components",
        [
            {"organization_id": org_id["华光窄线宽激光技术有限公司"], "component_category": "激光器企业", "product_name": "窄线宽稳频激光器", "supported_tech_routes": "离子阱;冷原子传感", "key_metrics": "线宽 < 1kHz，长期漂移低", "domestic_substitution": "是", "substitution_maturity": "中", "bottleneck_level": "高", "supply_capacity": "小批量", "delivery_cycle": "8-12周", "price_range": "20-80万元", "major_customers": "云阱量子;星图测量", "competitors": "海外激光品牌", "technical_barriers": "稳频和低噪声", "supply_chain_risks": "部分核心芯片进口", "interview_value": "高", "relevance_to_our_team": "高"},
            {"organization_id": org_id["北辰真空系统有限公司"], "component_category": "真空系统企业", "product_name": "UHV 真空腔", "supported_tech_routes": "离子阱;中性原子", "key_metrics": "极限真空、漏率、烘烤兼容性", "domestic_substitution": "是", "substitution_maturity": "中", "bottleneck_level": "中", "supply_capacity": "中批量", "delivery_cycle": "10-16周", "price_range": "30-150万元", "major_customers": "高校;云阱量子", "competitors": "进口真空系统", "technical_barriers": "洁净焊接和表面处理", "supply_chain_risks": "高端阀门", "interview_value": "高", "relevance_to_our_team": "高"},
            {"organization_id": org_id["极低温科学仪器股份有限公司"], "component_category": "低温系统企业", "product_name": "稀释制冷机", "supported_tech_routes": "超导量子", "key_metrics": "最低温、冷量、振动、稳定性", "domestic_substitution": "是", "substitution_maturity": "低", "bottleneck_level": "高", "supply_capacity": "样机", "delivery_cycle": "6-9个月", "price_range": "数百万元", "major_customers": "超导实验室", "competitors": "海外低温厂商", "technical_barriers": "低温工程和可靠性", "supply_chain_risks": "压缩机和阀门", "interview_value": "高", "relevance_to_our_team": "中"},
            {"organization_id": org_id["星衡测控电子有限公司"], "component_category": "AWG/FPGA/测控电子学企业", "product_name": "量子测控机箱", "supported_tech_routes": "超导量子;离子阱;NV色心", "key_metrics": "通道数、同步精度、采样率、抖动", "domestic_substitution": "是", "substitution_maturity": "中", "bottleneck_level": "高", "supply_capacity": "小批量", "delivery_cycle": "6-10周", "price_range": "50-300万元", "major_customers": "高校;量子整机公司", "competitors": "国际仪器厂商", "technical_barriers": "高速信号链和软件栈", "supply_chain_risks": "FPGA/DAC", "interview_value": "高", "relevance_to_our_team": "高"},
            {"organization_id": org_id["棱镜光学元件有限公司"], "component_category": "光学元件企业", "product_name": "低损耗镀膜光学件", "supported_tech_routes": "QKD;冷原子传感;离子阱", "key_metrics": "损耗、面型、镀膜一致性", "domestic_substitution": "是", "substitution_maturity": "中", "bottleneck_level": "中", "supply_capacity": "中批量", "delivery_cycle": "4-8周", "price_range": "数千到数万元", "major_customers": "QKD设备商;科研仪器厂商", "competitors": "海外光学件", "technical_barriers": "高端镀膜", "supply_chain_risks": "高纯材料", "interview_value": "中", "relevance_to_our_team": "中"},
        ],
    )
    insert_many(
        conn,
        "solution_providers",
        [
            {"organization_id": org_id["云阱量子计算有限公司"], "system_product_name": "离子阱量子计算整机", "product_form": "机柜式整机+云平台", "supported_tech_routes": "离子阱", "self_developed_parts": "控制软件、系统集成、部分阱芯片", "outsourced_parts": "激光器、真空、测控电子学", "system_metrics": "10-30 量子比特工程样机", "product_maturity": "工程样机", "commercialization_stage": "科研客户", "delivery_cases": "高校联合实验平台", "order_status": "试用订单", "revenue_status": "早期收入", "core_competence": "系统工程与算法云接口", "main_risks": "扩展性和应用价值"},
            {"organization_id": org_id["安密量子通信系统有限公司"], "system_product_name": "城域 QKD 网络方案", "product_form": "设备+密钥管理平台", "supported_tech_routes": "QKD", "self_developed_parts": "协议栈、密钥管理、系统集成", "outsourced_parts": "探测器、部分光学器件", "system_metrics": "城域传输、项目级稳定运行", "product_maturity": "小批量交付", "commercialization_stage": "示范项目", "delivery_cases": "政务安全网络", "order_status": "项目制订单", "revenue_status": "项目收入", "core_competence": "工程交付和安全集成", "main_risks": "需求复制和成本"},
            {"organization_id": org_id["星图量子测量科技有限公司"], "system_product_name": "量子磁力仪与冷原子重力仪", "product_form": "便携式仪器+场景算法", "supported_tech_routes": "NV色心;冷原子传感", "self_developed_parts": "传感头、控制软件、应用算法", "outsourced_parts": "激光器、光机件、真空组件", "system_metrics": "现场示范级灵敏度", "product_maturity": "小批量交付", "commercialization_stage": "行业客户", "delivery_cases": "电网检测示范", "order_status": "示范采购", "revenue_status": "增长初期", "core_competence": "场景落地和系统小型化", "main_risks": "现场可靠性"},
        ],
    )
    insert_many(
        conn,
        "downstream_customers",
        [
            {"organization_id": org_id["东湖量子信息研究院"], "customer_type": "高校科研院所", "industry": "科研", "application_scenario": "科研平台和成果转化", "specific_needs": "高可靠科研仪器和联合实验平台", "purchased_quantum_products": "激光器;真空系统;测控电子学", "potential_products": "离子阱整机;量子云服务", "budget_capacity": "中", "procurement_cycle": "6-12个月", "decision_chain": "课题组-平台-采购部门", "pain_points": "交付周期与定制化", "quantum_acceptance": "高", "demonstration_projects": "联合实验平台", "suppliers": "华光激光;北辰真空", "customer_feedback": "更关注稳定性和售后", "demand_strength": "高", "willingness_to_pay": "中", "interview_value": "高", "relevance_to_our_team": "高"},
            {"organization_id": org_id["华东通信运营商集团"], "customer_type": "通信运营商", "industry": "通信", "application_scenario": "政企专线量子安全通信", "specific_needs": "安全增强和示范网络", "purchased_quantum_products": "QKD设备", "potential_products": "量子安全通信平台", "budget_capacity": "高", "procurement_cycle": "12-24个月", "decision_chain": "技术部门-政企业务-采购", "pain_points": "标准、成本、客户付费", "quantum_acceptance": "中", "demonstration_projects": "城域安全通信试点", "suppliers": "安密量通", "customer_feedback": "项目价值需要绑定政企安全需求", "demand_strength": "中", "willingness_to_pay": "中", "interview_value": "高", "relevance_to_our_team": "中"},
            {"organization_id": org_id["国网量测技术中心"], "customer_type": "电网公司", "industry": "能源电力", "application_scenario": "地下管线、电缆缺陷和电磁环境检测", "specific_needs": "非接触高灵敏检测", "purchased_quantum_products": "量子磁力仪样机", "potential_products": "冷原子重力仪;量子磁力仪", "budget_capacity": "高", "procurement_cycle": "12个月以上", "decision_chain": "技术中心-试点单位-采购部门", "pain_points": "可靠性、标准、现场运维", "quantum_acceptance": "中", "demonstration_projects": "电网检测示范项目", "suppliers": "星图测量", "customer_feedback": "愿意试点但要求可量化提升", "demand_strength": "高", "willingness_to_pay": "中", "interview_value": "高", "relevance_to_our_team": "高"},
        ],
    )

    experts = [
        {"name": "陈启明", "institution": "东湖量子信息研究院", "title": "研究员", "country": "中国", "market_segment": "量子计算", "tech_routes": "离子阱", "expertise": "离子阱量子计算、量子门控制、系统工程", "representative_achievements": "离子阱多比特门控制实验", "representative_papers": "Ion trap system engineering review", "representative_patents": "离子阱芯片封装相关专利", "related_organizations": "云阱量子计算有限公司", "industrialization_experience": "参与企业联合实验室", "interview_value": "高", "credibility": "高", "relevance_to_our_team": "高", "contact": "chen@example.com", "key_views": "离子阱短期商业化更可能来自科研仪器和云平台，扩展性是核心验证点。", "risk_notes": "观点偏技术乐观", "source": "示例数据", "source_link": "", "created_at": NOW, "updated_at": NOW, "notes": "优先访谈"},
        {"name": "李澜", "institution": "长江大学量子器件中心", "title": "教授", "country": "中国", "market_segment": "量子计算", "tech_routes": "超导量子", "expertise": "超导芯片、低温测量、微波控制", "representative_achievements": "超导量子芯片工艺平台", "representative_papers": "Superconducting qubit fabrication", "representative_patents": "超导芯片制备专利", "related_organizations": "极低温科学仪器股份有限公司", "industrialization_experience": "与低温系统企业合作", "interview_value": "高", "credibility": "高", "relevance_to_our_team": "中", "contact": "li@example.com", "key_views": "低温系统和芯片一致性是国内产业链卡点。", "risk_notes": "需交叉验证商业判断", "source": "示例数据", "source_link": "", "created_at": NOW, "updated_at": NOW, "notes": ""},
        {"name": "王若安", "institution": "国家量子通信实验室", "title": "高级工程师", "country": "中国", "market_segment": "量子通信", "tech_routes": "QKD;量子网络", "expertise": "QKD系统、城域量子网络、安全标准", "representative_achievements": "多节点 QKD 示范网络", "representative_papers": "Practical QKD network deployment", "representative_patents": "密钥管理系统专利", "related_organizations": "安密量子通信系统有限公司", "industrialization_experience": "参与运营商示范项目", "interview_value": "高", "credibility": "高", "relevance_to_our_team": "中", "contact": "wang@example.com", "key_views": "QKD 的关键不是单设备指标，而是与政企安全需求绑定后的项目复制。", "risk_notes": "项目数据敏感", "source": "示例数据", "source_link": "", "created_at": NOW, "updated_at": NOW, "notes": ""},
        {"name": "赵清原", "institution": "南方精密测量研究所", "title": "研究员", "country": "中国", "market_segment": "量子精密测量", "tech_routes": "NV色心;冷原子传感", "expertise": "量子磁力仪、冷原子干涉、现场测量", "representative_achievements": "冷原子重力仪野外测试", "representative_papers": "Field quantum sensing systems", "representative_patents": "量子磁力仪探头专利", "related_organizations": "星图量子测量科技有限公司", "industrialization_experience": "参与电网和地质示范", "interview_value": "高", "credibility": "高", "relevance_to_our_team": "高", "contact": "zhao@example.com", "key_views": "精密测量的机会取决于现场可靠性和比传统设备更清晰的 ROI。", "risk_notes": "需更多客户侧访谈", "source": "示例数据", "source_link": "", "created_at": NOW, "updated_at": NOW, "notes": "客户需求判断价值高"},
    ]
    insert_many(conn, "experts", experts)

    interviews = [
        {"title": "离子阱专家访谈：科研仪器与云平台路径", "interviewee": "陈启明", "interviewee_type": "专家", "interview_date": "2026-03-12", "interviewer": "研究员A", "market_segment": "量子计算", "tech_routes": "离子阱", "related_organizations": "云阱量子计算有限公司;华光激光", "related_experts": "陈启明", "topic": "离子阱商业化路径与上游卡点", "raw_notes": "专家认为离子阱当前仍以科研客户为主，激光和真空稳定性影响系统可用性。", "key_points": "科研仪器和云平台是近期路径；上游稳定供应很关键。", "verifiable_facts": "云阱量子已有高校联合实验平台。", "subjective_judgments": "离子阱路线短期收入有限但技术壁垒高。", "important_conclusions": "应优先访谈激光、真空和测控供应商。", "risks": "扩展性验证不足。", "follow_up_actions": "安排华光激光供应链访谈。", "credibility": "高", "sensitivity": "内部", "information_type": "判断", "verification_status": "待验证", "source": "示例数据", "created_at": NOW, "updated_at": NOW},
        {"title": "云阱量子企业访谈：整机交付和供应链", "interviewee": "云阱量子计算有限公司", "interviewee_type": "企业", "interview_date": "2026-02-25", "interviewer": "研究员B", "market_segment": "量子计算", "tech_routes": "离子阱", "related_organizations": "云阱量子计算有限公司;北辰真空;星衡测控", "related_experts": "陈启明", "topic": "整机工程化与订单情况", "raw_notes": "公司处于工程样机阶段，有高校试用客户，采购外部激光和测控模块。", "key_points": "核心自研在系统集成和控制软件；外采核心部件较多。", "verifiable_facts": "已有高校联合实验平台。", "subjective_judgments": "供应链稳定性决定交付节奏。", "important_conclusions": "适合持续跟踪，但估值需谨慎。", "risks": "真实收入和续费情况待验证。", "follow_up_actions": "补充客户侧访谈。", "credibility": "中", "sensitivity": "保密", "information_type": "事实", "verification_status": "待验证", "source": "示例数据", "created_at": NOW, "updated_at": NOW},
        {"title": "电网客户访谈：量子磁力仪现场价值", "interviewee": "国网量测技术中心", "interviewee_type": "客户", "interview_date": "2026-01-18", "interviewer": "研究员A", "market_segment": "量子精密测量", "tech_routes": "NV色心;冷原子传感", "related_organizations": "国网量测技术中心;星图量子测量科技有限公司", "related_experts": "赵清原", "topic": "电力检测场景需求", "raw_notes": "客户愿意参与示范，但要求设备在现场可靠、易用，并证明相对传统方案的增量价值。", "key_points": "需求真实，但采购决策慢；现场运维比实验室指标更重要。", "verifiable_facts": "已有示范测试。", "subjective_judgments": "若能量化 ROI，付费意愿会提升。", "important_conclusions": "精密测量应优先做客户痛点验证。", "risks": "标准缺失和运维成本。", "follow_up_actions": "梳理电网检测指标体系。", "credibility": "高", "sensitivity": "内部", "information_type": "观点", "verification_status": "待验证", "source": "示例数据", "created_at": NOW, "updated_at": NOW},
        {"title": "供应链访谈：窄线宽激光器国产替代", "interviewee": "华光窄线宽激光技术有限公司", "interviewee_type": "供应商", "interview_date": "2026-04-09", "interviewer": "研究员C", "market_segment": "综合", "tech_routes": "离子阱;冷原子传感;NV色心", "related_organizations": "华光窄线宽激光技术有限公司;云阱量子计算有限公司", "related_experts": "", "topic": "激光器交付、指标和量子客户案例", "raw_notes": "供应商表示已服务多个量子客户，核心难点是稳频、噪声和定制波长。", "key_points": "有国产替代机会，交付周期明显影响整机企业。", "verifiable_facts": "存在量子客户案例但需名单验证。", "subjective_judgments": "激光器是离子阱和冷原子路线共同卡点。", "important_conclusions": "应建立核心激光供应商清单。", "risks": "部分核心芯片进口。", "follow_up_actions": "索取客户案例并交叉验证。", "credibility": "中", "sensitivity": "内部", "information_type": "判断", "verification_status": "存疑", "source": "示例数据", "created_at": NOW, "updated_at": NOW},
    ]
    insert_many(conn, "interviews", interviews)

    relationships = [
        {"source_organization_id": org_id["华光窄线宽激光技术有限公司"], "target_organization_id": org_id["云阱量子计算有限公司"], "relationship_type": "供应关系", "market_segment": "量子计算", "tech_routes": "离子阱", "description": "供应窄线宽激光器和稳频模块。", "event_date": "2025-10-01", "source": "访谈示例", "credibility": "中", "verification_status": "待验证", "notes": ""},
        {"source_organization_id": org_id["北辰真空系统有限公司"], "target_organization_id": org_id["云阱量子计算有限公司"], "relationship_type": "供应关系", "market_segment": "量子计算", "tech_routes": "离子阱", "description": "供应 UHV 真空腔和集成服务。", "event_date": "2025-09-01", "source": "访谈示例", "credibility": "中", "verification_status": "待验证", "notes": ""},
        {"source_organization_id": org_id["星衡测控电子有限公司"], "target_organization_id": org_id["云阱量子计算有限公司"], "relationship_type": "供应关系", "market_segment": "量子计算", "tech_routes": "离子阱", "description": "提供 AWG/FPGA 测控模块。", "event_date": "2025-11-15", "source": "访谈示例", "credibility": "低", "verification_status": "存疑", "notes": ""},
        {"source_organization_id": org_id["云阱量子计算有限公司"], "target_organization_id": org_id["东湖量子信息研究院"], "relationship_type": "合作关系", "market_segment": "量子计算", "tech_routes": "离子阱", "description": "联合建设离子阱实验平台。", "event_date": "2025-07-01", "source": "企业访谈", "credibility": "高", "verification_status": "已验证", "notes": ""},
        {"source_organization_id": org_id["安密量子通信系统有限公司"], "target_organization_id": org_id["华东通信运营商集团"], "relationship_type": "客户关系", "market_segment": "量子通信", "tech_routes": "QKD", "description": "参与城域安全通信示范项目。", "event_date": "2024-12-01", "source": "示例数据", "credibility": "中", "verification_status": "待验证", "notes": ""},
        {"source_organization_id": org_id["星图量子测量科技有限公司"], "target_organization_id": org_id["国网量测技术中心"], "relationship_type": "示范项目关系", "market_segment": "量子精密测量", "tech_routes": "NV色心;冷原子传感", "description": "开展电网检测示范测试。", "event_date": "2025-05-01", "source": "客户访谈", "credibility": "中", "verification_status": "待验证", "notes": ""},
        {"source_organization_id": org_id["启明量子基金"], "target_organization_id": org_id["华光窄线宽激光技术有限公司"], "relationship_type": "投资关系", "market_segment": "综合", "tech_routes": "离子阱;冷原子传感", "description": "参与 A 轮融资。", "event_date": "2025-04-12", "source": "融资示例", "credibility": "中", "verification_status": "待验证", "notes": ""},
        {"source_organization_id": org_id["云阱量子计算有限公司"], "target_organization_id": org_id["星图量子测量科技有限公司"], "relationship_type": "竞品关系", "market_segment": "综合", "tech_routes": "离子阱;冷原子传感", "description": "在部分科研仪器预算中竞争。", "event_date": "2026-01-01", "source": "研究员判断", "credibility": "低", "verification_status": "存疑", "notes": "仅为示例关系"},
    ]
    insert_many(conn, "industry_relationships", relationships)

    insert_many(
        conn,
        "papers",
        [
            {"title": "Scalable trapped-ion quantum processor engineering", "authors": "A. Chen et al.", "institutions": "Donghu Institute", "publish_date": "2025-09-10", "source": "arXiv", "abstract": "A modular trapped-ion engineering study.", "keywords": "ion trap;scaling;control", "market_segment": "量子计算", "tech_routes": "离子阱", "link": "https://arxiv.org/", "industrial_relevance": "提示模块化和自动化运维方向。"},
            {"title": "Neutral atom arrays for programmable simulation", "authors": "L. Smith et al.", "institutions": "Example Lab", "publish_date": "2025-12-02", "source": "Nature", "abstract": "Large neutral atom arrays.", "keywords": "neutral atom;Rydberg", "market_segment": "量子计算", "tech_routes": "中性原子", "link": "https://example.com", "industrial_relevance": "显示量子模拟潜力。"},
            {"title": "Field deployment of quantum magnetic sensing", "authors": "Q. Zhao et al.", "institutions": "Sensing Institute", "publish_date": "2026-02-14", "source": "IEEE", "abstract": "NV magnetometer field trial.", "keywords": "NV center;magnetometer", "market_segment": "量子精密测量", "tech_routes": "NV色心", "link": "https://example.com", "industrial_relevance": "贴近工业检测场景。"},
        ],
    )
    insert_many(
        conn,
        "patents",
        [
            {"title": "一种离子阱芯片封装结构", "patent_number": "CN000001", "applicants": "云阱量子计算有限公司", "application_date": "2025-03-01", "grant_status": "审中", "market_segment": "量子计算", "tech_routes": "离子阱", "abstract": "用于提高离子阱芯片封装稳定性。", "patent_type": "发明", "country": "中国", "related_organizations": "云阱量子计算有限公司", "related_experts": "陈启明"},
            {"title": "QKD 密钥管理系统", "patent_number": "CN000002", "applicants": "安密量子通信系统有限公司", "application_date": "2024-09-01", "grant_status": "授权", "market_segment": "量子通信", "tech_routes": "QKD", "abstract": "一种密钥管理和网络调度方法。", "patent_type": "发明", "country": "中国", "related_organizations": "安密量子通信系统有限公司", "related_experts": "王若安"},
            {"title": "便携式量子磁力仪探头", "patent_number": "CN000003", "applicants": "星图量子测量科技有限公司", "application_date": "2025-06-22", "grant_status": "审中", "market_segment": "量子精密测量", "tech_routes": "NV色心", "abstract": "面向现场检测的传感探头结构。", "patent_type": "发明", "country": "中国", "related_organizations": "星图量子测量科技有限公司", "related_experts": "赵清原"},
        ],
    )
    insert_many(
        conn,
        "financing_events",
        [
            {"organization_id": org_id["云阱量子计算有限公司"], "round": "A轮", "amount": "1.2亿元", "currency": "CNY", "financing_date": "2025-06-18", "investors": "湾区科创基金;高校成果转化基金", "valuation": "10-20亿元", "use_of_funds": "整机工程化和量子云平台", "source": "示例数据", "credibility": "中"},
            {"organization_id": org_id["安密量子通信系统有限公司"], "round": "B轮", "amount": "3亿元", "currency": "CNY", "financing_date": "2024-11-10", "investors": "国资平台;通信产业基金", "valuation": "20-30亿元", "use_of_funds": "城域网络交付和安全平台", "source": "示例数据", "credibility": "中"},
            {"organization_id": org_id["星图量子测量科技有限公司"], "round": "Pre-A轮", "amount": "5000万元", "currency": "CNY", "financing_date": "2025-03-30", "investors": "先进制造基金", "valuation": "5-10亿元", "use_of_funds": "产品小型化和客户示范", "source": "示例数据", "credibility": "中"},
        ],
    )
    insert_many(
        conn,
        "policies",
        [
            {"title": "量子科技产业创新行动计划", "region": "国家", "issuing_body": "示例部委", "publish_date": "2025-01-10", "market_segment": "综合", "tech_routes": "离子阱;超导量子;QKD;冷原子传感", "policy_tools": "平台建设;首台套;项目补贴", "funding_support": "专项资金", "target_entities": "企业;高校科研院所", "relevance_to_our_team": "高", "link": "https://example.com/policy"},
            {"title": "量子精密测量应用示范支持政策", "region": "华东", "issuing_body": "示例地方政府", "publish_date": "2025-07-20", "market_segment": "量子精密测量", "tech_routes": "NV色心;冷原子传感", "policy_tools": "示范项目;采购补贴", "funding_support": "最高500万元", "target_entities": "整机企业;下游客户", "relevance_to_our_team": "高", "link": "https://example.com/policy2"},
        ],
    )
    insert_many(
        conn,
        "products",
        [
            {"organization_id": org_id["云阱量子计算有限公司"], "product_name": "离子阱量子计算云平台", "product_type": "量子计算云平台", "market_segment": "量子计算", "tech_routes": "离子阱", "maturity": "工程样机", "application_scenario": "科研和教育", "target_customers": "高校;科研院所", "delivery_status": "试用", "revenue_status": "早期收入"},
            {"organization_id": org_id["安密量子通信系统有限公司"], "product_name": "QKD 城域安全网络方案", "product_type": "量子通信系统", "market_segment": "量子通信", "tech_routes": "QKD", "maturity": "小批量交付", "application_scenario": "政企安全通信", "target_customers": "运营商;政务;金融", "delivery_status": "示范项目", "revenue_status": "项目收入"},
            {"organization_id": org_id["星图量子测量科技有限公司"], "product_name": "量子磁力仪", "product_type": "量子精密测量设备", "market_segment": "量子精密测量", "tech_routes": "NV色心", "maturity": "小批量交付", "application_scenario": "电网和工业检测", "target_customers": "电网;工业检测客户", "delivery_status": "示范交付", "revenue_status": "增长初期"},
        ],
    )
    insert_many(
        conn,
        "research_tasks",
        [
            {"task_title": "验证云阱量子高校客户续费意愿", "task_type": "待验证问题", "related_market_segment": "量子计算", "related_tech_route": "离子阱", "related_organization": "云阱量子计算有限公司", "related_expert": "陈启明", "question_to_verify": "试用客户是否愿意付费续约？", "owner": "研究员A", "status": "进行中", "due_date": "2026-06-15", "created_at": NOW, "updated_at": NOW, "notes": "优先联系东湖量研院。"},
            {"task_title": "梳理激光器国产替代供应商清单", "task_type": "待补充数据", "related_market_segment": "综合", "related_tech_route": "离子阱;冷原子传感", "related_organization": "华光窄线宽激光技术有限公司", "related_expert": "", "question_to_verify": "国产激光器在量子客户中的稳定性表现如何？", "owner": "研究员C", "status": "未开始", "due_date": "2026-06-30", "created_at": NOW, "updated_at": NOW, "notes": ""},
            {"task_title": "访谈电网客户二次验证量子磁力仪 ROI", "task_type": "待访谈客户", "related_market_segment": "量子精密测量", "related_tech_route": "NV色心", "related_organization": "国网量测技术中心", "related_expert": "赵清原", "question_to_verify": "现场检测是否比传统方案有可量化提升？", "owner": "研究员B", "status": "未开始", "due_date": "2026-07-10", "created_at": NOW, "updated_at": NOW, "notes": ""},
        ],
    )
    conn.commit()
